import turtle

turtle.speed(10)
turtle.up()
turtle.setposition(-180, -140)
turtle.pensize(8)
turtle.pencolor('navy')
turtle.down()
turtle.forward(370)
turtle.backward(370)
turtle.left(105)
turtle.forward(50)
turtle.right(105)
turtle.forward(390)
turtle.left(80)
turtle.forward(200)
turtle.left(100)
turtle.forward(470)
turtle.left(105)
turtle.forward(155)
turtle.backward(210)
turtle.right(105)
turtle.forward(50)
turtle.up()

turtle.setposition(-120, -170)
turtle.color('black')
turtle.begin_fill()
turtle.circle(30)
turtle.end_fill()

turtle.setposition(120, -170)
turtle.color('black')
turtle.begin_fill()
turtle.circle(30)
turtle.end_fill()

turtle.setposition(-105, -90)
turtle.pensize(10)
turtle.pencolor('cyan')
turtle.down()
turtle.right(80)
turtle.forward(195)
turtle.backward(195)
turtle.right(100)
turtle.up()
turtle.forward(120)
turtle.left(90)
turtle.down()
turtle.forward(195)
turtle.backward(195)
turtle.right(88)
turtle.up()
turtle.forward(120)
turtle.left(78)
turtle.down()
turtle.forward(192)
turtle.left(12)
turtle.up()

turtle.setposition(-219, 47)
turtle.down()
turtle.right(92)
turtle.forward(437)
turtle.backward(437)
turtle.right(77)
turtle.up()
turtle.forward(70)
turtle.down()
turtle.left(77)
turtle.forward(410)

turtle.done()