import turtle

turtle.up()
turtle.setposition(0, 100)
turtle.down()
turtle.color('white', 'blue')
turtle.begin_fill()
turtle.left(90)
turtle.forward(100)
turtle.right(180)
turtle.forward(100)
turtle.left(50)
turtle.forward(100)
turtle.left(90)
turtle.circle(100, 130)
turtle.end_fill()

turtle.up()
turtle.setposition(0, 100)
turtle.down()
turtle.color('white', 'purple')
turtle.begin_fill()
turtle.right(60)
turtle.forward(100)
turtle.backward(100)
turtle.right(30)
turtle.forward(100)
turtle.left(90)
turtle.circle(100, 30)
turtle.end_fill()

turtle.up()
turtle.setposition(0, 100)
turtle.down()
turtle.color('white', 'green')
turtle.begin_fill()
turtle.right(25)
turtle.forward(100)
turtle.backward(100)
turtle.right(65)
turtle.forward(100)
turtle.left(90)
turtle.circle(100, 65)
turtle.end_fill()

turtle.up()
turtle.setposition(0, 100)
turtle.down()
turtle.color('white', 'yellow')
turtle.begin_fill()
turtle.right(15)
turtle.forward(100)
turtle.backward(100)
turtle.right(75)
turtle.forward(100)
turtle.left(90)
turtle.circle(100, 75)
turtle.end_fill()

turtle.up()
turtle.setposition(0, 100)
turtle.down()
turtle.color('white', 'red')
turtle.begin_fill()
turtle.right(30)
turtle.forward(100)
turtle.backward(100)
turtle.right(60)
turtle.forward(100)
turtle.left(90)
turtle.circle(100, 60)
turtle.end_fill()

turtle.done()